In [2]:
import IPython.display as ipd
import librosa
import librosa.display
import pandas as pd
import numpy as np
import soxr
import os

In [3]:
audio_path = "C:/Nini/Capstone/AudioFiles/Actor_01/01-01-02-01-01-01-01.wav"

In [4]:
x, sr = librosa.load(audio_path)
ipd.Audio(audio_path)

In [5]:
dataset = "C:/Nini/Capstone/AudioFiles/"
dataset_folders = os.listdir(dataset)
dataset_folders.sort()
dataset_folders


['Actor_01',
 'Actor_02',
 'Actor_03',
 'Actor_04',
 'Actor_05',
 'Actor_06',
 'Actor_07',
 'Actor_08',
 'Actor_09',
 'Actor_10',
 'Actor_11',
 'Actor_12',
 'Actor_13',
 'Actor_14',
 'Actor_15',
 'Actor_16',
 'Actor_17',
 'Actor_18',
 'Actor_19',
 'Actor_20',
 'Actor_21',
 'Actor_22',
 'Actor_23',
 'Actor_24']

In [6]:
emotions = []
gender = []
actor_ID = []
file_path = []
for folder in dataset_folders:
    file_name = os.listdir(dataset+folder)
    for file in file_name:
        filename = file.split('.')[0].split('-')
        emotions.append(int(filename[2]))
        actor_ID.append(int(filename[6]))
        bg = int(filename[6])
        if bg%2 == 0:
            gd = 'female'
        else:
            gd = 'male'
        gender.append(gd)
        file_path.append(dataset+folder+'/'+file)

print(emotions,gender,actor_ID,file_path)

[1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 

In [7]:
audio_df = pd.DataFrame(emotions)
audio_df = audio_df.replace({1:'neutral',2:'calm',3:'happy',4:'sad',5:'angry',6:'fearful',7:'disgust',8:'surprised'})
audio_df = pd.concat([pd.DataFrame(gender),audio_df,pd.DataFrame(actor_ID)],axis=1)
audio_df.columns = ['Gender','Emotion','Actor_ID']
audio_df = pd.concat([audio_df,pd.DataFrame(file_path, columns=['Path'])],axis=1)
audio_df

Gender    Emotion  Actor_ID  \
0       male    neutral         1   
1       male    neutral         1   
2       male    neutral         1   
3       male    neutral         1   
4       male       calm         1   
...      ...        ...       ...   
1435  female  surprised        24   
1436  female  surprised        24   
1437  female  surprised        24   
1438  female  surprised        24   
1439  female  surprised        24   

                                                   Path  
0     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-...  
1     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-...  
2     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-...  
3     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-...  
4     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-02-...  
...                                                 ...  
1435  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-...  
1436  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-...  
1437  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-...  
1438  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-...  
1439  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-...  

[1440 rows x 4 columns]

In [8]:
pd.set_option('display.max_colwidth', 1)

audio_df.sample(10)

Gender    Emotion  Actor_ID  \
277   male    fearful    5          
533   male    surprised  9          
1219  male    happy      21         
651   male    disgust    11         
996   male    fearful    17         
297   male    surprised  5          
1333  male    happy      23         
668   female  calm       12         
868   male    angry      15         
1374  male    surprised  23         

                                                               Path  
277   C:/Nini/Capstone/AudioFiles/Actor_05/01-01-06-01-01-02-05.wav  
533   C:/Nini/Capstone/AudioFiles/Actor_09/01-01-08-01-01-02-09.wav  
1219  C:/Nini/Capstone/AudioFiles/Actor_21/01-01-03-02-02-02-21.wav  
651   C:/Nini/Capstone/AudioFiles/Actor_11/01-01-07-02-02-02-11.wav  
996   C:/Nini/Capstone/AudioFiles/Actor_17/01-01-06-01-01-01-17.wav  
297   C:/Nini/Capstone/AudioFiles/Actor_05/01-01-08-02-01-02-05.wav  
1333  C:/Nini/Capstone/AudioFiles/Actor_23/01-01-03-01-01-02-23.wav  
668   C:/Nini/Capstone/AudioFiles/Actor_12/01-01-02-02-01-01-12.wav  
868   C:/Nini/Capstone/AudioFiles/Actor_15/01-01-05-01-01-01-15.wav  
1374  C:/Nini/Capstone/AudioFiles/Actor_23/01-01-08-01-02-01-23.wav

In [9]:
audio_df.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_dataset.csv')

In [12]:
df = pd.DataFrame(columns=['mfcc'])
counter = 0
for index, path in enumerate(audio_df.Path):
    X, sample_rate = librosa.load(path,res_type='kaiser_fast',duration=3,sr=44100,offset=0.5)
    audio_resampled = soxr.resample(X, sample_rate, 16000)
    # spectrogram = librosa.feature.melspectrogram(y=audio_resampled,sr=16000,n_mels=128,fmax=8000)
    # db_spec = librosa.power_to_db(spectrogram)
    # log_spectrogram = np.mean(db_spec,axis=1)

    mfcc = librosa.feature.mfcc(y=audio_resampled, sr=16000, n_mfcc=13)
    mfcc_mean = np.mean(mfcc, axis=1)

    # chroma = librosa.feature.chroma_stft(y=X, sr=16000, n_chroma=12)
    # chroma_mean = np.mean(chroma, axis=1)

    df.loc[counter] = [mfcc_mean]
    counter += 1


print(len(df))
print(df.head())

1440
                                                                                                                                                   mfcc
0  [-662.1679, 59.69811, 0.6110832, 17.169432, 3.8285017, -3.066584, -4.8663635, -12.571403, -8.595028, 2.2531755, -4.9913707, 2.6216257, -6.4781737]  
1  [-647.9788, 57.131824, -2.9471977, 22.008377, 1.3819733, -1.3404396, -6.673623, -14.953403, -7.200645, 2.0564756, -5.533809, 1.4856328, -6.5607953] 
2  [-644.2285, 59.25419, -1.4706599, 15.62812, -0.10539046, -1.2524807, -8.34238, -13.565615, -9.891212, 0.93992203, -5.2416615, 1.8930858, -7.5162845]
3  [-643.5373, 59.072308, 2.128592, 16.59148, 2.5751245, 1.3345902, -8.561844, -12.7883415, -8.964262, 1.2549844, -3.884624, 0.24988478, -6.9627824]   
4  [-676.8076, 66.46451, 2.297339, 18.638279, 3.3428264, -1.6125382, -7.3386464, -10.903287, -11.211803, 1.8135798, -6.014873, 0.9783365, -7.002045]   


In [13]:
df_combined = pd.concat([audio_df,pd.DataFrame(pd.DataFrame(df['mfcc'].values.tolist()))],axis=1)
df_combined = df_combined.fillna(0)

In [14]:
df_combined

Gender    Emotion  Actor_ID  \
0     male    neutral    1          
1     male    neutral    1          
2     male    neutral    1          
3     male    neutral    1          
4     male    calm       1          
...    ...     ...      ..          
1435  female  surprised  24         
1436  female  surprised  24         
1437  female  surprised  24         
1438  female  surprised  24         
1439  female  surprised  24         

                                                               Path  \
0     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-01-01-01-01.wav   
1     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-01-01-02-01.wav   
2     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-01-02-01-01.wav   
3     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-01-01-02-02-01.wav   
4     C:/Nini/Capstone/AudioFiles/Actor_01/01-01-02-01-01-01-01.wav   
...                                                             ...   
1435  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-01-02-02-24.wav   
1436  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-02-01-01-24.wav   
1437  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-02-01-02-24.wav   
1438  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-02-02-01-24.wav   
1439  C:/Nini/Capstone/AudioFiles/Actor_24/01-01-08-02-02-02-24.wav   

               0          1          2          3          4          5  \
0    -662.167908  59.698109  0.611083   17.169432  3.828502  -3.066584    
1    -647.978821  57.131824 -2.947198   22.008377  1.381973  -1.340440    
2    -644.228516  59.254189 -1.470660   15.628120 -0.105390  -1.252481    
3    -643.537292  59.072308  2.128592   16.591480  2.575125   1.334590    
4    -676.807617  66.464508  2.297339   18.638279  3.342826  -1.612538    
...          ...        ...       ...         ...       ...        ...    
1435 -543.035095  20.872150 -20.043970 -6.050778  -21.459932 -12.921358   
1436 -453.647980  42.130859 -23.844635 -10.280339 -26.985479 -14.747552   
1437 -461.246094  31.296865 -27.180576 -5.114043  -30.335985 -19.793079   
1438 -433.336823  25.894489 -7.050425  -1.864358  -15.922004 -5.953963    
1439 -471.717041  33.416866 -6.202348  -3.178908  -8.466023  -12.054789   

              6          7          8          9        10        11        12  
0    -4.866364  -12.571403 -8.595028   2.253175  -4.991371  2.621626 -6.478174  
1    -6.673623  -14.953403 -7.200645   2.056476  -5.533809  1.485633 -6.560795  
2    -8.342380  -13.565615 -9.891212   0.939922  -5.241662  1.893086 -7.516284  
3    -8.561844  -12.788342 -8.964262   1.254984  -3.884624  0.249885 -6.962782  
4    -7.338646  -10.903287 -11.211803  1.813580  -6.014873  0.978337 -7.002045  
...        ...         ...        ...       ...        ...       ...       ...  
1435 -26.793852 -9.228442  -10.791288 -9.417408  -6.563333 -5.072462  3.885188  
1436 -19.469170 -13.707332 -7.037307  -10.688368  4.831035 -1.728779  1.014995  
1437 -21.260378 -12.384166 -3.286028  -6.726067   4.548271 -4.345642 -0.388828  
1438 -19.133471 -1.106082  -7.013278  -5.237742  -6.211571 -6.034085  1.304743  
1439 -11.984494 -8.829656  -6.809122  -6.255657  -8.149495 -3.350336 -1.145245  

[1440 rows x 17 columns]

In [15]:
df_combined.drop(columns='Path',inplace=True)
df_combined.head()

Gender  Emotion  Actor_ID           0          1         2          3  \
0  male   neutral  1        -662.167908  59.698109  0.611083  17.169432   
1  male   neutral  1        -647.978821  57.131824 -2.947198  22.008377   
2  male   neutral  1        -644.228516  59.254189 -1.470660  15.628120   
3  male   neutral  1        -643.537292  59.072308  2.128592  16.591480   
4  male   calm     1        -676.807617  66.464508  2.297339  18.638279   

          4         5         6          7          8         9        10  \
0  3.828502 -3.066584 -4.866364 -12.571403 -8.595028   2.253175 -4.991371   
1  1.381973 -1.340440 -6.673623 -14.953403 -7.200645   2.056476 -5.533809   
2 -0.105390 -1.252481 -8.342380 -13.565615 -9.891212   0.939922 -5.241662   
3  2.575125  1.334590 -8.561844 -12.788342 -8.964262   1.254984 -3.884624   
4  3.342826 -1.612538 -7.338646 -10.903287 -11.211803  1.813580 -6.014873   

         11        12  
0  2.621626 -6.478174  
1  1.485633 -6.560795  
2  1.893086 -7.516284  
3  0.249885 -6.962782  
4  0.978337 -7.002045

In [16]:
df_combined.tail(5)

Gender    Emotion  Actor_ID           0          1          2  \
1435  female  surprised  24       -543.035095  20.872150 -20.043970   
1436  female  surprised  24       -453.647980  42.130859 -23.844635   
1437  female  surprised  24       -461.246094  31.296865 -27.180576   
1438  female  surprised  24       -433.336823  25.894489 -7.050425    
1439  female  surprised  24       -471.717041  33.416866 -6.202348    

              3          4          5          6          7          8  \
1435 -6.050778  -21.459932 -12.921358 -26.793852 -9.228442  -10.791288   
1436 -10.280339 -26.985479 -14.747552 -19.469170 -13.707332 -7.037307    
1437 -5.114043  -30.335985 -19.793079 -21.260378 -12.384166 -3.286028    
1438 -1.864358  -15.922004 -5.953963  -19.133471 -1.106082  -7.013278    
1439 -3.178908  -8.466023  -12.054789 -11.984494 -8.829656  -6.809122    

              9        10        11        12  
1435 -9.417408  -6.563333 -5.072462  3.885188  
1436 -10.688368  4.831035 -1.728779  1.014995  
1437 -6.726067   4.548271 -4.345642 -0.388828  
1438 -5.237742  -6.211571 -6.034085  1.304743  
1439 -6.255657  -8.149495 -3.350336 -1.145245

In [17]:
df_combined.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_dataset_mfcc_preprocessed.csv')

In [18]:
df_combined

Gender    Emotion  Actor_ID           0          1          2  \
0     male    neutral    1        -662.167908  59.698109  0.611083    
1     male    neutral    1        -647.978821  57.131824 -2.947198    
2     male    neutral    1        -644.228516  59.254189 -1.470660    
3     male    neutral    1        -643.537292  59.072308  2.128592    
4     male    calm       1        -676.807617  66.464508  2.297339    
...    ...     ...      ..                ...        ...       ...    
1435  female  surprised  24       -543.035095  20.872150 -20.043970   
1436  female  surprised  24       -453.647980  42.130859 -23.844635   
1437  female  surprised  24       -461.246094  31.296865 -27.180576   
1438  female  surprised  24       -433.336823  25.894489 -7.050425    
1439  female  surprised  24       -471.717041  33.416866 -6.202348    

              3          4          5          6          7          8  \
0     17.169432  3.828502  -3.066584  -4.866364  -12.571403 -8.595028    
1     22.008377  1.381973  -1.340440  -6.673623  -14.953403 -7.200645    
2     15.628120 -0.105390  -1.252481  -8.342380  -13.565615 -9.891212    
3     16.591480  2.575125   1.334590  -8.561844  -12.788342 -8.964262    
4     18.638279  3.342826  -1.612538  -7.338646  -10.903287 -11.211803   
...         ...       ...        ...        ...         ...        ...   
1435 -6.050778  -21.459932 -12.921358 -26.793852 -9.228442  -10.791288   
1436 -10.280339 -26.985479 -14.747552 -19.469170 -13.707332 -7.037307    
1437 -5.114043  -30.335985 -19.793079 -21.260378 -12.384166 -3.286028    
1438 -1.864358  -15.922004 -5.953963  -19.133471 -1.106082  -7.013278    
1439 -3.178908  -8.466023  -12.054789 -11.984494 -8.829656  -6.809122    

              9        10        11        12  
0     2.253175  -4.991371  2.621626 -6.478174  
1     2.056476  -5.533809  1.485633 -6.560795  
2     0.939922  -5.241662  1.893086 -7.516284  
3     1.254984  -3.884624  0.249885 -6.962782  
4     1.813580  -6.014873  0.978337 -7.002045  
...        ...        ...       ...       ...  
1435 -9.417408  -6.563333 -5.072462  3.885188  
1436 -10.688368  4.831035 -1.728779  1.014995  
1437 -6.726067   4.548271 -4.345642 -0.388828  
1438 -5.237742  -6.211571 -6.034085  1.304743  
1439 -6.255657  -8.149495 -3.350336 -1.145245  

[1440 rows x 16 columns]

In [46]:
from sklearn.model_selection import train_test_split

In [19]:
X = df_combined.iloc[:,3:]
Y = df_combined.iloc[:,:2].drop(columns=['Gender'])

In [20]:
X

0          1          2          3          4          5  \
0    -662.167908  59.698109  0.611083   17.169432  3.828502  -3.066584    
1    -647.978821  57.131824 -2.947198   22.008377  1.381973  -1.340440    
2    -644.228516  59.254189 -1.470660   15.628120 -0.105390  -1.252481    
3    -643.537292  59.072308  2.128592   16.591480  2.575125   1.334590    
4    -676.807617  66.464508  2.297339   18.638279  3.342826  -1.612538    
...          ...        ...       ...         ...       ...        ...    
1435 -543.035095  20.872150 -20.043970 -6.050778  -21.459932 -12.921358   
1436 -453.647980  42.130859 -23.844635 -10.280339 -26.985479 -14.747552   
1437 -461.246094  31.296865 -27.180576 -5.114043  -30.335985 -19.793079   
1438 -433.336823  25.894489 -7.050425  -1.864358  -15.922004 -5.953963    
1439 -471.717041  33.416866 -6.202348  -3.178908  -8.466023  -12.054789   

              6          7          8          9        10        11        12  
0    -4.866364  -12.571403 -8.595028   2.253175  -4.991371  2.621626 -6.478174  
1    -6.673623  -14.953403 -7.200645   2.056476  -5.533809  1.485633 -6.560795  
2    -8.342380  -13.565615 -9.891212   0.939922  -5.241662  1.893086 -7.516284  
3    -8.561844  -12.788342 -8.964262   1.254984  -3.884624  0.249885 -6.962782  
4    -7.338646  -10.903287 -11.211803  1.813580  -6.014873  0.978337 -7.002045  
...        ...         ...        ...       ...        ...       ...       ...  
1435 -26.793852 -9.228442  -10.791288 -9.417408  -6.563333 -5.072462  3.885188  
1436 -19.469170 -13.707332 -7.037307  -10.688368  4.831035 -1.728779  1.014995  
1437 -21.260378 -12.384166 -3.286028  -6.726067   4.548271 -4.345642 -0.388828  
1438 -19.133471 -1.106082  -7.013278  -5.237742  -6.211571 -6.034085  1.304743  
1439 -11.984494 -8.829656  -6.809122  -6.255657  -8.149495 -3.350336 -1.145245  

[1440 rows x 13 columns]

In [21]:
Y

Emotion
0     neutral  
1     neutral  
2     neutral  
3     neutral  
4     calm     
...    ...     
1435  surprised
1436  surprised
1437  surprised
1438  surprised
1439  surprised

[1440 rows x 1 columns]

In [22]:
mean = np.mean(X,axis=0)
std = np.std(X,axis=0)
X = (X - mean)/std

In [23]:
extracted_features = pd.concat([X,Y],axis=1)

In [24]:
extracted_features

0         1         2         3         4         5         6  \
0    -1.222256  0.435453  0.687748  0.684265  1.164671  0.413157  1.241263   
1    -1.089801  0.300611  0.449501  1.158819  0.927349  0.630154  0.994529   
2    -1.054792  0.412128  0.548363  0.533109  0.783069  0.641211  0.766704   
3    -1.048340  0.402571  0.789354  0.627585  1.043089  0.966437  0.736742   
4    -1.358917  0.790984  0.800652  0.828314  1.117559  0.595948  0.903737   
...        ...       ...       ...       ...       ...       ...       ...   
1435 -0.110156 -1.604605 -0.695225 -1.592935 -1.288401 -0.825708 -1.752364   
1436  0.724269 -0.487595 -0.949701 -2.007727 -1.824400 -1.055282 -0.752370   
1437  0.653341 -1.056852 -1.173062 -1.501070 -2.149412 -1.689566 -0.996912   
1438  0.913873 -1.340713  0.174766 -1.182374 -0.751202  0.050178 -0.706539   
1439  0.555595 -0.945460  0.231550 -1.311292 -0.027944 -0.716769  0.269468   

             7         8         9        10        11        12    Emotion  
0    -0.340933 -0.468779  0.995929  0.400123  0.760254 -0.412211  neutral    
1    -0.729282 -0.206501  0.961108  0.296353  0.541058 -0.428949  neutral    
2    -0.503024 -0.712587  0.763451  0.352241  0.619678 -0.622512  neutral    
3    -0.376302 -0.538231  0.819225  0.611846  0.302613 -0.510384  neutral    
4    -0.068973 -0.960986  0.918110  0.204324  0.443172 -0.518337  calm       
...        ...       ...       ...       ...       ...       ...   ...       
1435  0.204085 -0.881888 -1.070046  0.099403 -0.724362  1.687207  surprised  
1436 -0.526129 -0.175777 -1.295036  2.279171 -0.079181  1.105761  surprised  
1437 -0.310407  0.529825 -0.593613  2.225078 -0.584119  0.821373  surprised  
1438  1.528310 -0.171258 -0.330144  0.166695 -0.909913  1.164458  surprised  
1439  0.269101 -0.132856 -0.510339 -0.204034 -0.392069  0.668138  surprised  

[1440 rows x 14 columns]

In [25]:
extracted_features.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_extracted_features_mfcc.csv')

In [ ]:
# train, test = train_test_split(df_combined, test_size=0.2,random_state=0,stratify=df_combined[['Emotion','Gender','Actor_ID']])

In [ ]:
# X_train = train.iloc[:, 3:] #Considering only the features here (they start from the 3rd column.)
# y_train = train.iloc[:,:2].drop(columns=['Gender'])#Since we need only want to identify the emotion,we have used this.

In [ ]:
# y_train

Emotion
692   angry    
472   surprised
1312  surprised
1439  surprised
896   surprised
...         ...
1231  angry    
1107  sad      
20    sad      
605   calm     
38    fearful  

[1152 rows x 1 columns]

In [ ]:
# X_test = test.iloc[:,3:]
# y_test = test.iloc[:,:2].drop(columns=['Gender'])

In [ ]:
# y_test

Emotion
220   fearful
1211  calm   
917   happy  
695   angry  
1360  fearful
...       ...
166   disgust
428   calm   
731   calm   
83    sad    
1411  angry  

[288 rows x 1 columns]

In [ ]:
# mean = np.mean(X_train, axis=0)
# std = np.std(X_train, axis=0)
# X_train = (X_train - mean)/std
# X_test = (X_test - mean)/std

In [ ]:
# X_train

0         1         2         3         4         5         6  \
692   1.411868  1.345495  1.342727  1.330829  1.324083  1.314427  1.299692   
472  -0.124024 -0.121139 -0.141735 -0.173062 -0.177504 -0.193086 -0.168106   
1312 -0.268843 -0.304935 -0.305892 -0.294066 -0.282139 -0.293246 -0.313937   
1439  2.041975  2.204845  2.140447  2.086630  2.120548  2.019480  1.880927   
896   0.551877  0.508320  0.491658  0.472505  0.463040  0.469951  0.460641   
...        ...       ...       ...       ...       ...       ...       ...   
1231  0.998028  0.939111  0.936788  0.981236  1.072696  1.057531  0.952013   
1107  0.185672 -0.051901 -0.190230 -0.209356 -0.220337 -0.237565 -0.235701   
20   -1.015321 -1.037965 -1.038118 -1.040031 -1.043928 -1.048024 -1.050038   
605  -1.284739 -1.013279 -1.048582 -1.334130 -1.203706 -1.029993 -0.987110   
38   -0.470280 -0.502743 -0.503483 -0.503338 -0.512175 -0.517519 -0.522390   

             7         8         9  ...       249       250       251  \
692   1.282448  1.267560  1.254837  ...  0.082503  0.018905  0.013918   
472  -0.181819 -0.190645 -0.177890  ... -0.542821 -0.577925 -0.573217   
1312 -0.332324 -0.336304 -0.337589  ... -0.610209 -0.640974 -0.636825   
1439  1.841170  1.863453  1.827138  ... -0.288452 -0.338712 -0.339688   
896   0.434623  0.430670  0.428886  ...  2.087561  1.934802  1.935756   
...        ...       ...       ...  ...       ...       ...       ...   
1231  0.901146  0.874623  0.862735  ... -0.098533 -0.157915 -0.159121   
1107 -0.240304 -0.259852 -0.264179  ... -0.573714 -0.610067 -0.596625   
20   -1.049516 -1.048652 -1.044857  ... -0.905099 -0.922529 -0.918031   
605  -1.001327 -0.951095 -0.903040  ...  2.087561  1.934802  1.935756   
38   -0.525858 -0.528531 -0.528445  ... -0.572017 -0.593344 -0.579699   

           252       253       254       255       256       257       258  
692   0.026165  0.040508 -0.056596 -0.057297 -0.152086 -0.138870 -0.113974  
472  -0.568127 -0.569940 -0.623907 -0.610287 -0.686128 -0.692841 -0.699784  
1312 -0.632129 -0.627898 -0.684544 -0.682704 -0.751584 -0.752680 -0.750391  
1439 -0.334369 -0.326423 -0.394240 -0.380284 -0.466433 -0.471695 -0.475656  
896   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
...        ...       ...       ...       ...       ...       ...       ...  
1231 -0.147752 -0.137368 -0.224509 -0.224445 -0.315998 -0.318825 -0.318692  
1107 -0.587449 -0.586159 -0.642623 -0.633244 -0.704354 -0.711927 -0.704608  
20   -0.913013 -0.908604 -0.950304 -0.948595 -1.004771 -1.005754 -1.002635  
605   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
38   -0.383399 -0.098883  1.746733  1.749771  1.564674  1.562536  1.557235  

[1152 rows x 259 columns]

In [ ]:
# # ONE HOT ENCODE THE TARGET
# # CNN REQUIRES INPUT AND OUTPUT ARE NUMBERS
# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.utils import to_categorical
# lb = LabelEncoder()
# y_train = to_categorical(lb.fit_transform(y_train))
# y_test = to_categorical(lb.fit_transform(y_test))

# print(y_test[0:10])
# #Since,there are 8 different emotions; we get 8 columns.
# #The places where 1 is present represents that particular emotion.

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]


c:\Nini\Capstone\src\capstone_env\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# X_train

0         1         2         3         4         5         6  \
692   1.411868  1.345495  1.342727  1.330829  1.324083  1.314427  1.299692   
472  -0.124024 -0.121139 -0.141735 -0.173062 -0.177504 -0.193086 -0.168106   
1312 -0.268843 -0.304935 -0.305892 -0.294066 -0.282139 -0.293246 -0.313937   
1439  2.041975  2.204845  2.140447  2.086630  2.120548  2.019480  1.880927   
896   0.551877  0.508320  0.491658  0.472505  0.463040  0.469951  0.460641   
...        ...       ...       ...       ...       ...       ...       ...   
1231  0.998028  0.939111  0.936788  0.981236  1.072696  1.057531  0.952013   
1107  0.185672 -0.051901 -0.190230 -0.209356 -0.220337 -0.237565 -0.235701   
20   -1.015321 -1.037965 -1.038118 -1.040031 -1.043928 -1.048024 -1.050038   
605  -1.284739 -1.013279 -1.048582 -1.334130 -1.203706 -1.029993 -0.987110   
38   -0.470280 -0.502743 -0.503483 -0.503338 -0.512175 -0.517519 -0.522390   

             7         8         9  ...       249       250       251  \
692   1.282448  1.267560  1.254837  ...  0.082503  0.018905  0.013918   
472  -0.181819 -0.190645 -0.177890  ... -0.542821 -0.577925 -0.573217   
1312 -0.332324 -0.336304 -0.337589  ... -0.610209 -0.640974 -0.636825   
1439  1.841170  1.863453  1.827138  ... -0.288452 -0.338712 -0.339688   
896   0.434623  0.430670  0.428886  ...  2.087561  1.934802  1.935756   
...        ...       ...       ...  ...       ...       ...       ...   
1231  0.901146  0.874623  0.862735  ... -0.098533 -0.157915 -0.159121   
1107 -0.240304 -0.259852 -0.264179  ... -0.573714 -0.610067 -0.596625   
20   -1.049516 -1.048652 -1.044857  ... -0.905099 -0.922529 -0.918031   
605  -1.001327 -0.951095 -0.903040  ...  2.087561  1.934802  1.935756   
38   -0.525858 -0.528531 -0.528445  ... -0.572017 -0.593344 -0.579699   

           252       253       254       255       256       257       258  
692   0.026165  0.040508 -0.056596 -0.057297 -0.152086 -0.138870 -0.113974  
472  -0.568127 -0.569940 -0.623907 -0.610287 -0.686128 -0.692841 -0.699784  
1312 -0.632129 -0.627898 -0.684544 -0.682704 -0.751584 -0.752680 -0.750391  
1439 -0.334369 -0.326423 -0.394240 -0.380284 -0.466433 -0.471695 -0.475656  
896   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
...        ...       ...       ...       ...       ...       ...       ...  
1231 -0.147752 -0.137368 -0.224509 -0.224445 -0.315998 -0.318825 -0.318692  
1107 -0.587449 -0.586159 -0.642623 -0.633244 -0.704354 -0.711927 -0.704608  
20   -0.913013 -0.908604 -0.950304 -0.948595 -1.004771 -1.005754 -1.002635  
605   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
38   -0.383399 -0.098883  1.746733  1.749771  1.564674  1.562536  1.557235  

[1152 rows x 259 columns]

In [ ]:
# y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])