In [3]:
import IPython.display as ipd
import librosa
import librosa.display
import pandas as pd
import numpy as np
import soxr
import os

In [1]:
audio_path = "C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-02-01-01-01-01_1.wav"

In [5]:
x, sr = librosa.load(audio_path)
ipd.Audio(audio_path)

In [6]:
dataset = "C:/Nini/Capstone/AudioFilesSnippets/"
dataset_folders = os.listdir(dataset)
dataset_folders.sort()
dataset_folders


['Actor_01',
 'Actor_02',
 'Actor_03',
 'Actor_04',
 'Actor_05',
 'Actor_06',
 'Actor_07',
 'Actor_08',
 'Actor_09',
 'Actor_10',
 'Actor_11',
 'Actor_12',
 'Actor_13',
 'Actor_14',
 'Actor_15',
 'Actor_16',
 'Actor_17',
 'Actor_18',
 'Actor_19',
 'Actor_20',
 'Actor_21',
 'Actor_22',
 'Actor_23',
 'Actor_24']

In [7]:
emotions = []
gender = []
actor_ID = []
file_path = []
for folder in dataset_folders:
    file_name = os.listdir(dataset+folder)
    for file in file_name:
        filename = file.split('.')[0].split('-')
        emotions.append(int(filename[2]))
        actor_ID.append(int(filename[6]))
        bg = int(filename[6])
        if bg%2 == 0:
            gd = 'female'
        else:
            gd = 'male'
        gender.append(gd)
        file_path.append(dataset+folder+'/'+file)

print(emotions,gender,actor_ID,file_path)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 

In [8]:
audio_df = pd.DataFrame(emotions)
audio_df = audio_df.replace({1:'neutral',2:'calm',3:'happy',4:'sad',5:'angry',6:'fearful',7:'disgust',8:'surprised'})
audio_df = pd.concat([pd.DataFrame(gender),audio_df,pd.DataFrame(actor_ID)],axis=1)
audio_df.columns = ['Gender','Emotion','Actor_ID']
audio_df = pd.concat([audio_df,pd.DataFrame(file_path, columns=['Path'])],axis=1)
audio_df

Gender    Emotion  Actor_ID  \
0     female    neutral        10   
1       male    neutral        11   
2     female    neutral        12   
3     female    neutral        10   
4       male    neutral        11   
...      ...        ...       ...   
5232  female  surprised       240   
5233    male  surprised       241   
5234  female  surprised       242   
5235    male  surprised       243   
5236  female  surprised       244   

                                                   Path  
0     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/0...  
1     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/0...  
2     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/0...  
3     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/0...  
4     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/0...  
...                                                 ...  
5232  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/0...  
5233  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/0...  
5234  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/0...  
5235  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/0...  
5236  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/0...  

[5237 rows x 4 columns]

In [9]:
pd.set_option('display.max_colwidth', 1)

audio_df.sample(10)

Gender    Emotion  Actor_ID  \
2351  female  neutral    122        
2639  male    sad        133        
4106  male    happy      203        
4518  male    surprised  211        
1287  female  disgust    64         
324   male    sad        23         
2045  male    angry      103        
2806  female  happy      144        
3184  male    neutral    161        
1878  female  disgust    90         

                                                                         Path  
2351  C:/Nini/Capstone/AudioFilesSnippets/Actor_12/01-01-01-01-02-02-12_2.wav  
2639  C:/Nini/Capstone/AudioFilesSnippets/Actor_13/01-01-04-01-01-01-13_3.wav  
4106  C:/Nini/Capstone/AudioFilesSnippets/Actor_20/01-01-03-01-01-02-20_3.wav  
4518  C:/Nini/Capstone/AudioFilesSnippets/Actor_21/01-01-08-01-02-02-21_1.wav  
1287  C:/Nini/Capstone/AudioFilesSnippets/Actor_06/01-01-07-02-01-01-06_4.wav  
324   C:/Nini/Capstone/AudioFilesSnippets/Actor_02/01-01-04-02-01-02-02_3.wav  
2045  C:/Nini/Capstone/AudioFilesSnippets/Actor_10/01-01-05-02-02-02-10_3.wav  
2806  C:/Nini/Capstone/AudioFilesSnippets/Actor_14/01-01-03-02-01-02-14_4.wav  
3184  C:/Nini/Capstone/AudioFilesSnippets/Actor_16/01-01-01-01-02-02-16_1.wav  
1878  C:/Nini/Capstone/AudioFilesSnippets/Actor_09/01-01-07-02-02-01-09_0.wav

In [10]:
audio_df.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_dataset_snippets.csv')

In [11]:
df = pd.DataFrame(columns=['mel_spectrogram','mfcc','chroma'])
counter = 0
for index, path in enumerate(audio_df.Path):
    X, sample_rate = librosa.load(path,res_type='kaiser_fast',duration=3,sr=16000,offset=0.5)
    spectrogram = librosa.feature.melspectrogram(y=X,sr=16000,n_mels=128,fmax=8000)
    db_spec = librosa.power_to_db(spectrogram)
    log_spectrogram = np.mean(db_spec,axis=1)

    mfcc = librosa.feature.mfcc(y=X, sr=16000, n_mfcc=13)
    mfcc_mean = np.mean(mfcc, axis=1)

    chroma = librosa.feature.chroma_stft(y=X, sr=16000, n_chroma=12)
    chroma_mean = np.mean(chroma, axis=1)

    df.loc[counter] = [log_spectrogram, mfcc_mean, chroma_mean]
    counter += 1


print(len(df))
print(df.head())

c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\librosa\core\pitch.py:101: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning

5237
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [12]:
print(counter)
print(spectrogram.shape)
print(db_spec.shape)
print(log_spectrogram.shape)
print(len(log_spectrogram))
log_spectrogram

5237
(128, 16)
(128, 16)
(128,)
128


array([-48.031303, -47.430805, -50.35661 , -51.09178 , -56.993458,
       -58.304226, -59.901646, -60.905876, -61.377945, -59.93245 ,
       -60.97785 , -63.199757, -64.9135  , -66.42602 , -64.63027 ,
       -62.619225, -61.860764, -66.55159 , -67.92459 , -66.95203 ,
       -67.216644, -65.96382 , -65.753784, -69.1311  , -70.82384 ,
       -71.29912 , -73.82335 , -72.066086, -72.47828 , -72.61035 ,
       -72.92247 , -73.0152  , -74.90192 , -74.69154 , -73.14912 ,
       -72.88187 , -72.907974, -72.95416 , -72.268005, -76.015945,
       -72.69056 , -72.18321 , -72.07124 , -72.4554  , -73.09851 ,
       -71.51753 , -71.106255, -72.99924 , -75.10432 , -74.84331 ,
       -74.75154 , -75.11708 , -74.43034 , -73.5535  , -71.60349 ,
       -72.40808 , -74.50797 , -74.08293 , -74.11803 , -73.808044,
       -73.104614, -72.33906 , -73.76784 , -73.69905 , -74.1228  ,
       -74.00415 , -74.52459 , -74.63476 , -73.58507 , -73.71982 ,
       -73.88539 , -73.19631 , -74.36487 , -75.44611 , -76.430

In [13]:
df_combined = pd.concat([audio_df,pd.DataFrame(df['mel_spectrogram'].values.tolist()),pd.DataFrame(df['mfcc'].values.tolist()),pd.DataFrame(df['chroma'].values.tolist())],axis=1)
df_combined = df_combined.fillna(0)

In [14]:
df_combined

Gender    Emotion  Actor_ID  \
0     female  neutral    10         
1     male    neutral    11         
2     female  neutral    12         
3     female  neutral    10         
4     male    neutral    11         
...    ...        ...    ..         
5232  female  surprised  240        
5233  male    surprised  241        
5234  female  surprised  242        
5235  male    surprised  243        
5236  female  surprised  244        

                                                                         Path  \
0     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-01-01-01-01-01_0.wav   
1     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-01-01-01-01-01_1.wav   
2     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-01-01-01-01-01_2.wav   
3     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-01-01-01-02-01_0.wav   
4     C:/Nini/Capstone/AudioFilesSnippets/Actor_01/01-01-01-01-01-02-01_1.wav   
...                                                                       ...   
5232  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/01-01-08-02-02-02-24_0.wav   
5233  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/01-01-08-02-02-02-24_1.wav   
5234  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/01-01-08-02-02-02-24_2.wav   
5235  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/01-01-08-02-02-02-24_3.wav   
5236  C:/Nini/Capstone/AudioFilesSnippets/Actor_24/01-01-08-02-02-02-24_4.wav   

              0          1          2          3          4          5  ...  \
0    -52.786026 -45.583466 -34.059448 -14.904263 -11.806824 -22.142227  ...   
1    -55.714336 -47.235538 -32.437531 -25.120844 -34.152279 -44.781273  ...   
2    -60.636795 -61.195198 -62.003254 -65.503357 -71.087914 -73.080811  ...   
3    -53.665459 -44.370083 -37.727516 -19.209730 -9.802891  -15.656280  ...   
4    -54.774132 -42.125359 -29.733917 -20.767223 -30.779823 -40.504662  ...   
...         ...        ...        ...        ...        ...        ...  ...   
5232 -35.712105 -36.294437 -38.212585 -39.106255 -37.814335 -36.495377  ...   
5233 -37.976440 -39.050537 -41.419624 -40.938904 -41.593147 -40.745308  ...   
5234 -36.226646 -35.048828 -36.120079 -36.618713 -38.205963 -37.881142  ...   
5235 -26.033216 -30.436846 -36.966553 -39.854797 -43.399471 -43.933174  ...   
5236 -48.031303 -47.430805 -50.356609 -51.091782 -56.993458 -58.304226  ...   

             2         3         4         5         6         7         8  \
0     0.336765  0.290293  0.258015  0.152400  0.207013  0.363961  0.431656   
1     0.239073  0.219083  0.392201  0.526160  0.462934  0.412537  0.548171   
2     0.288233  0.314147  0.368165  0.385106  0.414939  0.385863  0.423479   
3     0.503968  0.217009  0.225192  0.395282  0.147583  0.115569  0.215081   
4     0.209739  0.291098  0.486335  0.559513  0.551810  0.421002  0.481575   
...        ...       ...       ...       ...       ...       ...       ...   
5232  0.340991  0.390446  0.288727  0.529631  0.523398  0.506241  0.337220   
5233  0.153247  0.150110  0.148681  0.279524  0.396969  0.597821  0.549794   
5234  0.297071  0.218874  0.187432  0.208638  0.188960  0.291980  0.442904   
5235  0.485209  0.481742  0.504093  0.519782  0.527903  0.559586  0.608894   
5236  0.589247  0.576458  0.611872  0.722005  0.807222  0.853803  0.654452   

             9        10        11  
0     0.419612  0.359502  0.311342  
1     0.516350  0.543938  0.468114  
2     0.511225  0.980081  0.912249  
3     0.349155  0.540218  0.419644  
4     0.424019  0.353263  0.420855  
...        ...       ...       ...  
5232  0.223562  0.315025  0.232653  
5233  0.482961  0.482402  0.267835  
5234  0.346043  0.388528  0.549784  
5235  0.627884  0.771938  0.806495  
5236  0.627889  0.777135  0.770159  

[5237 rows x 157 columns]

In [15]:
df_combined.drop(columns='Path',inplace=True)
df_combined.head()

Gender  Emotion  Actor_ID          0          1          2          3  \
0  female  neutral  10       -52.786026 -45.583466 -34.059448 -14.904263   
1  male    neutral  11       -55.714336 -47.235538 -32.437531 -25.120844   
2  female  neutral  12       -60.636795 -61.195198 -62.003254 -65.503357   
3  female  neutral  10       -53.665459 -44.370083 -37.727516 -19.209730   
4  male    neutral  11       -54.774132 -42.125359 -29.733917 -20.767223   

           4          5          6  ...         2         3         4  \
0 -11.806824 -22.142227 -26.915251  ...  0.336765  0.290293  0.258015   
1 -34.152279 -44.781273 -35.628056  ...  0.239073  0.219083  0.392201   
2 -71.087914 -73.080811 -68.991425  ...  0.288233  0.314147  0.368165   
3 -9.802891  -15.656280 -27.147839  ...  0.503968  0.217009  0.225192   
4 -30.779823 -40.504662 -30.872259  ...  0.209739  0.291098  0.486335   

          5         6         7         8         9        10        11  
0  0.152400  0.207013  0.363961  0.431656  0.419612  0.359502  0.311342  
1  0.526160  0.462934  0.412537  0.548171  0.516350  0.543938  0.468114  
2  0.385106  0.414939  0.385863  0.423479  0.511225  0.980081  0.912249  
3  0.395282  0.147583  0.115569  0.215081  0.349155  0.540218  0.419644  
4  0.559513  0.551810  0.421002  0.481575  0.424019  0.353263  0.420855  

[5 rows x 156 columns]

In [16]:
df_combined.tail(5)

Gender    Emotion  Actor_ID          0          1          2          3  \
5232  female  surprised  240      -35.712105 -36.294437 -38.212585 -39.106255   
5233  male    surprised  241      -37.976440 -39.050537 -41.419624 -40.938904   
5234  female  surprised  242      -36.226646 -35.048828 -36.120079 -36.618713   
5235  male    surprised  243      -26.033216 -30.436846 -36.966553 -39.854797   
5236  female  surprised  244      -48.031303 -47.430805 -50.356609 -51.091782   

              4          5          6  ...         2         3         4  \
5232 -37.814335 -36.495377 -36.790318  ...  0.340991  0.390446  0.288727   
5233 -41.593147 -40.745308 -40.255524  ...  0.153247  0.150110  0.148681   
5234 -38.205963 -37.881142 -35.383251  ...  0.297071  0.218874  0.187432   
5235 -43.399471 -43.933174 -46.239754  ...  0.485209  0.481742  0.504093   
5236 -56.993458 -58.304226 -59.901646  ...  0.589247  0.576458  0.611872   

             5         6         7         8         9        10        11  
5232  0.529631  0.523398  0.506241  0.337220  0.223562  0.315025  0.232653  
5233  0.279524  0.396969  0.597821  0.549794  0.482961  0.482402  0.267835  
5234  0.208638  0.188960  0.291980  0.442904  0.346043  0.388528  0.549784  
5235  0.519782  0.527903  0.559586  0.608894  0.627884  0.771938  0.806495  
5236  0.722005  0.807222  0.853803  0.654452  0.627889  0.777135  0.770159  

[5 rows x 156 columns]

In [17]:
df_combined.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_dataset_mel_mfcc_chroma_preprocessed_snippets.csv')

In [18]:
df_combined

Gender    Emotion  Actor_ID          0          1          2          3  \
0     female  neutral    10       -52.786026 -45.583466 -34.059448 -14.904263   
1     male    neutral    11       -55.714336 -47.235538 -32.437531 -25.120844   
2     female  neutral    12       -60.636795 -61.195198 -62.003254 -65.503357   
3     female  neutral    10       -53.665459 -44.370083 -37.727516 -19.209730   
4     male    neutral    11       -54.774132 -42.125359 -29.733917 -20.767223   
...    ...        ...    ..              ...        ...        ...        ...   
5232  female  surprised  240      -35.712105 -36.294437 -38.212585 -39.106255   
5233  male    surprised  241      -37.976440 -39.050537 -41.419624 -40.938904   
5234  female  surprised  242      -36.226646 -35.048828 -36.120079 -36.618713   
5235  male    surprised  243      -26.033216 -30.436846 -36.966553 -39.854797   
5236  female  surprised  244      -48.031303 -47.430805 -50.356609 -51.091782   

              4          5          6  ...         2         3         4  \
0    -11.806824 -22.142227 -26.915251  ...  0.336765  0.290293  0.258015   
1    -34.152279 -44.781273 -35.628056  ...  0.239073  0.219083  0.392201   
2    -71.087914 -73.080811 -68.991425  ...  0.288233  0.314147  0.368165   
3    -9.802891  -15.656280 -27.147839  ...  0.503968  0.217009  0.225192   
4    -30.779823 -40.504662 -30.872259  ...  0.209739  0.291098  0.486335   
...         ...        ...        ...  ...       ...       ...       ...   
5232 -37.814335 -36.495377 -36.790318  ...  0.340991  0.390446  0.288727   
5233 -41.593147 -40.745308 -40.255524  ...  0.153247  0.150110  0.148681   
5234 -38.205963 -37.881142 -35.383251  ...  0.297071  0.218874  0.187432   
5235 -43.399471 -43.933174 -46.239754  ...  0.485209  0.481742  0.504093   
5236 -56.993458 -58.304226 -59.901646  ...  0.589247  0.576458  0.611872   

             5         6         7         8         9        10        11  
0     0.152400  0.207013  0.363961  0.431656  0.419612  0.359502  0.311342  
1     0.526160  0.462934  0.412537  0.548171  0.516350  0.543938  0.468114  
2     0.385106  0.414939  0.385863  0.423479  0.511225  0.980081  0.912249  
3     0.395282  0.147583  0.115569  0.215081  0.349155  0.540218  0.419644  
4     0.559513  0.551810  0.421002  0.481575  0.424019  0.353263  0.420855  
...        ...       ...       ...       ...       ...       ...       ...  
5232  0.529631  0.523398  0.506241  0.337220  0.223562  0.315025  0.232653  
5233  0.279524  0.396969  0.597821  0.549794  0.482961  0.482402  0.267835  
5234  0.208638  0.188960  0.291980  0.442904  0.346043  0.388528  0.549784  
5235  0.519782  0.527903  0.559586  0.608894  0.627884  0.771938  0.806495  
5236  0.722005  0.807222  0.853803  0.654452  0.627889  0.777135  0.770159  

[5237 rows x 156 columns]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = df_combined.iloc[:,3:]
Y = df_combined.iloc[:,:2].drop(columns=['Gender'])

In [21]:
X

0          1          2          3          4          5  \
0    -52.786026 -45.583466 -34.059448 -14.904263 -11.806824 -22.142227   
1    -55.714336 -47.235538 -32.437531 -25.120844 -34.152279 -44.781273   
2    -60.636795 -61.195198 -62.003254 -65.503357 -71.087914 -73.080811   
3    -53.665459 -44.370083 -37.727516 -19.209730 -9.802891  -15.656280   
4    -54.774132 -42.125359 -29.733917 -20.767223 -30.779823 -40.504662   
...         ...        ...        ...        ...        ...        ...   
5232 -35.712105 -36.294437 -38.212585 -39.106255 -37.814335 -36.495377   
5233 -37.976440 -39.050537 -41.419624 -40.938904 -41.593147 -40.745308   
5234 -36.226646 -35.048828 -36.120079 -36.618713 -38.205963 -37.881142   
5235 -26.033216 -30.436846 -36.966553 -39.854797 -43.399471 -43.933174   
5236 -48.031303 -47.430805 -50.356609 -51.091782 -56.993458 -58.304226   

              6          7          8          9  ...         2         3  \
0    -26.915251 -22.946404 -13.897753 -13.925696  ...  0.336765  0.290293   
1    -35.628056 -31.840992 -29.111500 -36.053459  ...  0.239073  0.219083   
2    -68.991425 -71.236877 -73.249496 -74.580658  ...  0.288233  0.314147   
3    -27.147839 -27.646265 -18.840073 -12.771875  ...  0.503968  0.217009   
4    -30.872259 -27.131371 -28.143581 -32.508743  ...  0.209739  0.291098   
...         ...        ...        ...        ...  ...       ...       ...   
5232 -36.790318 -36.250233 -34.055244 -30.757334  ...  0.340991  0.390446   
5233 -40.255524 -36.855854 -29.571152 -26.732876  ...  0.153247  0.150110   
5234 -35.383251 -30.318928 -23.202581 -21.275991  ...  0.297071  0.218874   
5235 -46.239754 -43.646370 -35.272598 -29.359190  ...  0.485209  0.481742   
5236 -59.901646 -60.905876 -61.377945 -59.932449  ...  0.589247  0.576458   

             4         5         6         7         8         9        10  \
0     0.258015  0.152400  0.207013  0.363961  0.431656  0.419612  0.359502   
1     0.392201  0.526160  0.462934  0.412537  0.548171  0.516350  0.543938   
2     0.368165  0.385106  0.414939  0.385863  0.423479  0.511225  0.980081   
3     0.225192  0.395282  0.147583  0.115569  0.215081  0.349155  0.540218   
4     0.486335  0.559513  0.551810  0.421002  0.481575  0.424019  0.353263   
...        ...       ...       ...       ...       ...       ...       ...   
5232  0.288727  0.529631  0.523398  0.506241  0.337220  0.223562  0.315025   
5233  0.148681  0.279524  0.396969  0.597821  0.549794  0.482961  0.482402   
5234  0.187432  0.208638  0.188960  0.291980  0.442904  0.346043  0.388528   
5235  0.504093  0.519782  0.527903  0.559586  0.608894  0.627884  0.771938   
5236  0.611872  0.722005  0.807222  0.853803  0.654452  0.627889  0.777135   

            11  
0     0.311342  
1     0.468114  
2     0.912249  
3     0.419644  
4     0.420855  
...        ...  
5232  0.232653  
5233  0.267835  
5234  0.549784  
5235  0.806495  
5236  0.770159  

[5237 rows x 153 columns]

In [22]:
Y

Emotion
0     neutral  
1     neutral  
2     neutral  
3     neutral  
4     neutral  
...       ...  
5232  surprised
5233  surprised
5234  surprised
5235  surprised
5236  surprised

[5237 rows x 1 columns]

In [23]:
mean = np.mean(X,axis=0)
std = np.std(X,axis=0)
X = (X - mean)/std

In [24]:
extracted_features = pd.concat([X,Y],axis=1)

In [25]:
extracted_features

0         1         2         3         4         5         6  \
0    -0.761053  0.061246  0.987961  1.976733  1.904703  1.026698  0.477335   
1    -0.987029 -0.091738  1.123508  1.276300  0.540515 -0.300174 -0.004582   
2    -1.366893 -1.384418 -1.347355 -1.492263 -1.714403 -1.958806 -1.849958   
3    -0.828918  0.173606  0.681414  1.681556  2.027043  1.406839  0.464471   
4    -0.914474  0.381470  1.349454  1.574777  0.746403 -0.049522  0.258468   
...        ...       ...       ...       ...       ...       ...       ...   
5232  0.556533  0.921420  0.640876  0.317481  0.316947  0.185462 -0.068869   
5233  0.381795  0.666202  0.372857  0.191838  0.086250 -0.063626 -0.260534   
5234  0.516826  1.036765  0.815751  0.488023  0.293038  0.104242  0.008958   
5235  1.303448  1.463840  0.745009  0.266162 -0.024026 -0.250467 -0.591530   
5236 -0.394133 -0.109820 -0.374023 -0.504228 -0.853937 -1.092752 -1.347189   

             7         8         9  ...         3         4         5  \
0     0.598487  0.927866  0.877900  ... -0.328262 -0.579112 -1.221518   
1     0.127678  0.169147 -0.200578  ... -0.713798  0.137202  0.600907   
2    -1.957632 -2.032043 -2.078343  ... -0.199114  0.008890 -0.086860   
3     0.349714  0.681389  0.934136  ... -0.725022 -0.754331 -0.037245   
4     0.376968  0.217418 -0.027813  ... -0.323902  0.639710  0.763534   
...        ...       ...       ...  ...       ...       ...       ...   
5232 -0.105713 -0.077401  0.057548  ...  0.213971 -0.415165  0.617835   
5233 -0.137770  0.146224  0.253695  ... -1.087217 -1.162763 -0.601672   
5234  0.208244  0.463828  0.519657  ... -0.714927 -0.955900 -0.947304   
5235 -0.497207 -0.138111  0.125692  ...  0.708256  0.734506  0.569807   
5236 -1.410789 -1.440001 -1.364409  ...  1.221051  1.309854  1.555831   

             6         7         8         9        10        11    Emotion  
0    -0.962952 -0.248147  0.041572  0.001957 -0.367970 -0.448514  neutral    
1     0.366214 -0.006261  0.624011  0.490459  0.416651  0.214855  neutral    
2     0.116943 -0.139087  0.000698  0.464581  2.272068  2.094186  neutral    
3    -1.271612 -1.485025 -1.041041 -0.353829  0.400825  0.009757  neutral    
4     0.827806  0.035889  0.291109  0.024215 -0.394510  0.014883  neutral    
...        ...       ...       ...       ...       ...       ...      ...    
5232  0.680241  0.460343 -0.430494 -0.988044 -0.557183 -0.781482  surprised  
5233  0.023614  0.916368  0.632124  0.321856  0.154864 -0.632610  surprised  
5234 -1.056716 -0.606581  0.097798 -0.369546 -0.244487  0.560439  surprised  
5235  0.703641  0.725976  0.927553  1.053679  1.386598  1.646694  surprised  
5236  2.154326  2.191045  1.155290  1.053702  1.408703  1.492941  surprised  

[5237 rows x 154 columns]

In [26]:
extracted_features.to_csv(f'C:/Nini/Capstone/CSV_Files/ravdess_extracted_features_mel_mfcc_chroma_snippets.csv')

In [ ]:
# train, test = train_test_split(df_combined, test_size=0.2,random_state=0,stratify=df_combined[['Emotion','Gender','Actor_ID']])

In [ ]:
# X_train = train.iloc[:, 3:] #Considering only the features here (they start from the 3rd column.)
# y_train = train.iloc[:,:2].drop(columns=['Gender'])#Since we need only want to identify the emotion,we have used this.

In [ ]:
# y_train

Emotion
692   angry    
472   surprised
1312  surprised
1439  surprised
896   surprised
...         ...
1231  angry    
1107  sad      
20    sad      
605   calm     
38    fearful  

[1152 rows x 1 columns]

In [ ]:
# X_test = test.iloc[:,3:]
# y_test = test.iloc[:,:2].drop(columns=['Gender'])

In [ ]:
# y_test

Emotion
220   fearful
1211  calm   
917   happy  
695   angry  
1360  fearful
...       ...
166   disgust
428   calm   
731   calm   
83    sad    
1411  angry  

[288 rows x 1 columns]

In [ ]:
# mean = np.mean(X_train, axis=0)
# std = np.std(X_train, axis=0)
# X_train = (X_train - mean)/std
# X_test = (X_test - mean)/std

In [ ]:
# X_train

0         1         2         3         4         5         6  \
692   1.411868  1.345495  1.342727  1.330829  1.324083  1.314427  1.299692   
472  -0.124024 -0.121139 -0.141735 -0.173062 -0.177504 -0.193086 -0.168106   
1312 -0.268843 -0.304935 -0.305892 -0.294066 -0.282139 -0.293246 -0.313937   
1439  2.041975  2.204845  2.140447  2.086630  2.120548  2.019480  1.880927   
896   0.551877  0.508320  0.491658  0.472505  0.463040  0.469951  0.460641   
...        ...       ...       ...       ...       ...       ...       ...   
1231  0.998028  0.939111  0.936788  0.981236  1.072696  1.057531  0.952013   
1107  0.185672 -0.051901 -0.190230 -0.209356 -0.220337 -0.237565 -0.235701   
20   -1.015321 -1.037965 -1.038118 -1.040031 -1.043928 -1.048024 -1.050038   
605  -1.284739 -1.013279 -1.048582 -1.334130 -1.203706 -1.029993 -0.987110   
38   -0.470280 -0.502743 -0.503483 -0.503338 -0.512175 -0.517519 -0.522390   

             7         8         9  ...       249       250       251  \
692   1.282448  1.267560  1.254837  ...  0.082503  0.018905  0.013918   
472  -0.181819 -0.190645 -0.177890  ... -0.542821 -0.577925 -0.573217   
1312 -0.332324 -0.336304 -0.337589  ... -0.610209 -0.640974 -0.636825   
1439  1.841170  1.863453  1.827138  ... -0.288452 -0.338712 -0.339688   
896   0.434623  0.430670  0.428886  ...  2.087561  1.934802  1.935756   
...        ...       ...       ...  ...       ...       ...       ...   
1231  0.901146  0.874623  0.862735  ... -0.098533 -0.157915 -0.159121   
1107 -0.240304 -0.259852 -0.264179  ... -0.573714 -0.610067 -0.596625   
20   -1.049516 -1.048652 -1.044857  ... -0.905099 -0.922529 -0.918031   
605  -1.001327 -0.951095 -0.903040  ...  2.087561  1.934802  1.935756   
38   -0.525858 -0.528531 -0.528445  ... -0.572017 -0.593344 -0.579699   

           252       253       254       255       256       257       258  
692   0.026165  0.040508 -0.056596 -0.057297 -0.152086 -0.138870 -0.113974  
472  -0.568127 -0.569940 -0.623907 -0.610287 -0.686128 -0.692841 -0.699784  
1312 -0.632129 -0.627898 -0.684544 -0.682704 -0.751584 -0.752680 -0.750391  
1439 -0.334369 -0.326423 -0.394240 -0.380284 -0.466433 -0.471695 -0.475656  
896   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
...        ...       ...       ...       ...       ...       ...       ...  
1231 -0.147752 -0.137368 -0.224509 -0.224445 -0.315998 -0.318825 -0.318692  
1107 -0.587449 -0.586159 -0.642623 -0.633244 -0.704354 -0.711927 -0.704608  
20   -0.913013 -0.908604 -0.950304 -0.948595 -1.004771 -1.005754 -1.002635  
605   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
38   -0.383399 -0.098883  1.746733  1.749771  1.564674  1.562536  1.557235  

[1152 rows x 259 columns]

In [ ]:
# # ONE HOT ENCODE THE TARGET
# # CNN REQUIRES INPUT AND OUTPUT ARE NUMBERS
# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.utils import to_categorical
# lb = LabelEncoder()
# y_train = to_categorical(lb.fit_transform(y_train))
# y_test = to_categorical(lb.fit_transform(y_test))

# print(y_test[0:10])
# #Since,there are 8 different emotions; we get 8 columns.
# #The places where 1 is present represents that particular emotion.

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]


c:\Nini\Capstone\src\capstone_env\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Nini\Capstone\src\capstone_env\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# X_train

0         1         2         3         4         5         6  \
692   1.411868  1.345495  1.342727  1.330829  1.324083  1.314427  1.299692   
472  -0.124024 -0.121139 -0.141735 -0.173062 -0.177504 -0.193086 -0.168106   
1312 -0.268843 -0.304935 -0.305892 -0.294066 -0.282139 -0.293246 -0.313937   
1439  2.041975  2.204845  2.140447  2.086630  2.120548  2.019480  1.880927   
896   0.551877  0.508320  0.491658  0.472505  0.463040  0.469951  0.460641   
...        ...       ...       ...       ...       ...       ...       ...   
1231  0.998028  0.939111  0.936788  0.981236  1.072696  1.057531  0.952013   
1107  0.185672 -0.051901 -0.190230 -0.209356 -0.220337 -0.237565 -0.235701   
20   -1.015321 -1.037965 -1.038118 -1.040031 -1.043928 -1.048024 -1.050038   
605  -1.284739 -1.013279 -1.048582 -1.334130 -1.203706 -1.029993 -0.987110   
38   -0.470280 -0.502743 -0.503483 -0.503338 -0.512175 -0.517519 -0.522390   

             7         8         9  ...       249       250       251  \
692   1.282448  1.267560  1.254837  ...  0.082503  0.018905  0.013918   
472  -0.181819 -0.190645 -0.177890  ... -0.542821 -0.577925 -0.573217   
1312 -0.332324 -0.336304 -0.337589  ... -0.610209 -0.640974 -0.636825   
1439  1.841170  1.863453  1.827138  ... -0.288452 -0.338712 -0.339688   
896   0.434623  0.430670  0.428886  ...  2.087561  1.934802  1.935756   
...        ...       ...       ...  ...       ...       ...       ...   
1231  0.901146  0.874623  0.862735  ... -0.098533 -0.157915 -0.159121   
1107 -0.240304 -0.259852 -0.264179  ... -0.573714 -0.610067 -0.596625   
20   -1.049516 -1.048652 -1.044857  ... -0.905099 -0.922529 -0.918031   
605  -1.001327 -0.951095 -0.903040  ...  2.087561  1.934802  1.935756   
38   -0.525858 -0.528531 -0.528445  ... -0.572017 -0.593344 -0.579699   

           252       253       254       255       256       257       258  
692   0.026165  0.040508 -0.056596 -0.057297 -0.152086 -0.138870 -0.113974  
472  -0.568127 -0.569940 -0.623907 -0.610287 -0.686128 -0.692841 -0.699784  
1312 -0.632129 -0.627898 -0.684544 -0.682704 -0.751584 -0.752680 -0.750391  
1439 -0.334369 -0.326423 -0.394240 -0.380284 -0.466433 -0.471695 -0.475656  
896   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
...        ...       ...       ...       ...       ...       ...       ...  
1231 -0.147752 -0.137368 -0.224509 -0.224445 -0.315998 -0.318825 -0.318692  
1107 -0.587449 -0.586159 -0.642623 -0.633244 -0.704354 -0.711927 -0.704608  
20   -0.913013 -0.908604 -0.950304 -0.948595 -1.004771 -1.005754 -1.002635  
605   1.937509  1.940116  1.746733  1.749771  1.564674  1.562536  1.557235  
38   -0.383399 -0.098883  1.746733  1.749771  1.564674  1.562536  1.557235  

[1152 rows x 259 columns]

In [ ]:
# y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])